pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'dotnet restore'
                    sh 'dotnet build --configuration Release'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'dotnet test --no-restore'
                }
            }
        }
    }
}
